### PR TITLE
Record egg harvest location

### PR DESCRIPTION
**Pull request by wotnak**
Adds location to the egg harvest log if the asset for which the egg harvest is recorded has location set.

### CODE REVIEW

**Review by mstenta — CHANGES_REQUESTED** [review]
This looks good to me @wotnak!

The only issue I found was: if you have two animals in the same location, that location gets added to the harvest log twice.

Here is a screenshot:

Screenshot from 2023-09-11 11-52-01

I wonder if this is the responsibility of this module, or a broader farmOS issue, though. Logs really shouldn't have duplicate references on them.

**Comment by mstenta** [comment]
farmOS does include this module: https://www.drupal.org/project/entity_reference_validators

However, that only deals with *validation*, but we do not run `$log->validate()` when the quick form is submitted. This is something @paul121 and I discussed more broadly with regard to quick forms: should they automatically call `$entity->validate()` on any entity created by the helper methods, and prevent submission if it doesn't work? This would essentially break the quick form for the user, though, and it would be the responsibility of the quick form developer to fix it in their code. But it would prevent invalid entities from being saved.

So in general I think it is the responsibility of the quick form developers to make sure that entities are valid, but in this case I wonder if farmOS should also provide some automatic de-duplication logic that removes duplicate entity references when entities are saved.

**Comment by mstenta** [comment]
In other words... maybe we should actually merge this as-is, and follow up with that kind of de-dupe logic in farmOS core... what do you think?

**Comment by wotnak** [comment]
Pushed a fix. But some automatic deduplication on entity save could also be nice to ensure entity reference field values are saved always without duplicates, even when created without triggering entity validation.

**Comment by paul121** [comment]
This LGTM. I agree we could/should make those changes but can happen outside this PR since it is now fixed here. I wonder if validation in quick forms is something we can provide without making any breaking changes to those "quick" APIs? :thinking:

**Comment by mstenta** [comment]
Thanks @wotnak and @paul121 - merged!

**Pull request merged**
